# Generated by Django 5.2.6 on 2025-09-28 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cuisine",
                    models.CharField(
                        choices=[
                            ("american", "American"),
                            ("asian_fusion", "Asian Fusion"),
                            ("barbecue", "Barbecue"),
                            ("bakery", "Bakery"),
                            ("breakfast", "Breakfast & Brunch"),
                            ("cafe", "Cafe"),
                            ("chinese", "Chinese"),
                            ("fine_dining", "Fine Dining"),
                            ("french", "French"),
                            ("greek", "Greek"),
                            ("indian", "Indian"),
                            ("italian", "Italian"),
                            ("japanese", "Japanese"),
                            ("korean", "Korean"),
                            ("latin", "Latin"),
                            ("mediterranean", "Mediterranean"),
                            ("mexican", "Mexican"),
                            ("pizza", "Pizza"),
                            ("pub", "Pub"),
                            ("seafood", "Seafood"),
                            ("southern", "Southern"),
                            ("steakhouse", "Steakhouse"),
                            ("sushi", "Sushi"),
                            ("tacos", "Tacos"),
                            ("thai", "Thai"),
                            ("vegan", "Vegan"),
                            ("vietnamese", "Vietnamese"),
                            ("wine_bar", "Wine Bar"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "price_tier",
                    models.PositiveSmallIntegerField(
                        help_text="Price level on a scale from 1 (budget) to 4 (splurge).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_open_now", models.BooleanField(default=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.CharField(max_length=500)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("short_description", models.CharField(max_length=280)),
                ("hours", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-average_rating", "name"],
                "indexes": [
                    models.Index(
                        fields=["cuisine"], name="restaurants_cuisine_6e1775_idx"
                    ),
                    models.Index(
                        fields=["price_tier"], name="restaurants_price_t_c9d290_idx"
                    ),
                    models.Index(
                        fields=["is_open_now"], name="restaurants_is_open_882503_idx"
                    ),
                ],
            },
        ),
    ]
